version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  commands:
    - pip install poetry
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry run sphinx-build -b html docs $READTHEDOCS_OUTPUT/html